name: nkust_ap
description: A new Flutter application.

version: 3.1.12+30112

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  #official plugin
  shared_preferences: ^0.5.3+1
  package_info: ^0.4.0+4
  url_launcher: ^5.0.3
  share: ^0.6.1+1
  connectivity: ^0.4.2
  firebase_core: ^0.4.0+3
  firebase_analytics: ^3.0.2
  firebase_remote_config: ^0.2.0+2
  firebase_messaging: ^5.0.2
  http: ^0.12.0+2
  #third party plugin
  dio: 2.1.0
  toast: ^0.1.4
  tuple: ^1.0.1
  flutter_crashlytics:
    git: https://github.com/abc873693/flutter_crashlytics
  encrypt: ^2.0.0
  flutter_local_notifications: ^0.8.0
  sprintf: ^4.0.2
  add_2_calendar: ^1.3.0
  cached_network_image: ^1.1.1
  app_review: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/images/
