name: nkust_ap
description: A new Flutter application.

version: 3.3.0+30300

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  #official plugin
  shared_preferences: 0.5.3+4
  package_info: 0.4.0+6
  url_launcher: 5.3.0
  share: 0.6.2+3
  image_picker: 0.6.1+4
  path_provider: 1.3.0
  firebase_core: 0.4.0+9
  firebase_analytics: 5.0.2
  firebase_remote_config: 0.2.0+7
  firebase_messaging: 5.1.6
  firebase_crashlytics: 0.1.0+3
  http: 0.12.0+2
  html: 0.14.0+2
  http_parser: 3.1.3
  #third party plugin
  dio: 3.0.3
  toast: 0.1.4
  tuple: 1.0.2
  encrypt: 3.3.1
  flutter_local_notifications: 0.8.4
  sprintf: 4.0.2
  add_2_calendar: 1.3.0
  cached_network_image: 1.1.1
  app_review: 1.0.0
  outline_material_icons: 0.1.0
  photo_view: 0.5.0
  date_range_picker: 1.0.6
  flutter_autofill: 0.4.1
  image: 2.1.4
  flutter_native_image: 0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/images/
  - assets/leave_campus_data.json
