name: Build Test
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.x'
          channel: 'dev'
      - run: flutter pub get
      - name: Analyze files
        run: flutter analyze .
      - name: Model test
        run: flutter test test/model_test.dart

  build_ios:
    name: Build iOS App
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.x'
          channel: 'dev'
      - run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign

  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.x' # you can use 1.12
          channel: 'dev'
      - name: Upgrades flutter
        run: flutter upgrade
      - run: flutter pub get
      - name: Build Android app bundle
        run: flutter build appbundle --release

  build_web:
    name: Build Web App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.x'
          channel: 'dev'
      - name: Upgrades flutter
        run: flutter upgrade
      - name: Enable Web
        run: flutter config --enable-web
      - run: flutter pub get
      - name: Build Web
        run: flutter build web